[package]
name = "lessons"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
hello_macro_derive = { path = "../macros/hello_macro_derive" }
rand = "0.8.5"
