# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "DIY"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "const_initialization"
path = "src/cpp_comparison/const_initialization.rs"

[[bin]]
name = "use_after_free"
path = "src/cpp_comparison/use_after_free.rs"

[[bin]]
name = "data_race"
path = "src/cpp_comparison/data_race.rs"

[[bin]]
name = "move_semantics"
path = "src/cpp_comparison/move_semantics.rs"

[[bin]]
name = "references"
path = "src/cpp_comparison/references.rs"

[[bin]]
name = "variable_shadowing"
path = "src/cpp_comparison/variable_shadowing.rs"

[[bin]]
name = "constants"
path = "src/lessons/constants.rs"

[[bin]]
name = "type_infer"
path = "src/lessons/type_infer.rs"

[[bin]]
name = "data_types"
path = "src/lessons/data_types.rs"

[[bin]]
name = "functions"
path = "src/lessons/functions.rs"

[[bin]]
name = "control_flow"
path = "src/lessons/control_flow.rs"

[[bin]]
name = "guessing_game"
path = "src/practices/guessing_game.rs"

[[bin]]
name = "fibonacci"
path = "src/practices/fibonacci.rs"

[[bin]]
name = "temperature_conversions"
path = "src/practices/temperature_conversions.rs"

[[bin]]
name = "the_twelve_days_of_christmas"
path = "src/practices/the_twelve_days_of_christmas.rs"

[dependencies]
rand = "0.8.5"
