# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "const_initialization"
path = "src/cpp_comparison/const_initialization.rs"

[[bin]]
name = "use_after_free"
path = "src/cpp_comparison/use_after_free.rs"

[[bin]]
name = "data_race"
path = "src/cpp_comparison/data_race.rs"

[[bin]]
name = "move_semantics"
path = "src/cpp_comparison/move_semantics.rs"
