# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "DIY"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "const_initialization"
path = "src/cpp_comparison/const_initialization.rs"

[[bin]]
name = "use_after_free"
path = "src/cpp_comparison/use_after_free.rs"

[[bin]]
name = "data_race"
path = "src/cpp_comparison/data_race.rs"

[[bin]]
name = "move_semantics"
path = "src/cpp_comparison/move_semantics.rs"

[[bin]]
name = "references"
path = "src/cpp_comparison/references.rs"

[[bin]]
name = "variable_shadowing"
path = "src/cpp_comparison/variable_shadowing.rs"

[[bin]]
name = "constants"
path = "src/lessons/constants.rs"

[[bin]]
name = "guessing_game"
path = "src/practices/guessing_game.rs"

[dependencies]
rand = "0.8.5"
